review:
  auto_review:
    enabled: true
    target_branches: ["develop", "main"]
  comments:
    inline: true
    summary: true
  rules:
    - "Respecter Clean Architecture et DDD"
    - "Gestion des erreurs avec ProblemDetail RFC 7807"
    - "Tests unitaires obligatoires > 80% coverage"
    - "Qualiter du code "
    - "Evolution continue"
    - "respect cahier de charge et code base "