
services:
  postgres:
    image: postgres:16-alpine
    container_name: securetrack-postgres
    environment:
      POSTGRES_DB: securetrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: