spring:
  application:
    name: package-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/securetrack}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8085

# Gestion des erreurs
app:
  error:
    enabled: true