server:
  port: 8084

spring:
  application:
    name: tracking-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/cbsdb}
    username: ${DB_USERNAME:cbsuser}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:cbsuser}
    password: ${RABBITMQ_PASSWORD}

security:
  tracking:
    username: ${SECURITY_USERNAME:admin}
    password: ${SECURITY_PASSWORD}

axon:
  axonserver:
    enabled: false
  serializer:
    general: jackson

logging:
  level:
    com.cbs.logistics.tracking_service: INFO
